const char HTML_BODY[] =
"<!DOCTYPE html><html lang=\"pt-br\"><head>"
"<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Observação Meteorológica</title>"
"<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;"
"background:#667eea;color:#fff;display:flex;justify-content:center;align-items:center;"
"min-height:100vh;padding:20px}.container{width:100%;max-width:480px;background:"
"rgba(255,255,255,0.1);backdrop-filter:blur(20px);border-radius:16px;padding:20px}"
".title{text-align:center;font-size:1.6rem;margin-bottom:20px;font-weight:300}"
".status{margin-bottom:15px;text-align:center;padding:10px;border-radius:8px;font-weight:bold}"
".ok{background:rgba(46,204,113,0.25);border:2px solid #2ecc71}.error{background:"
"rgba(231,76,60,0.25);border:2px solid #e74c3c}.form{display:grid;gap:10px;background:"
"rgba(255,255,255,0.1);backdrop-filter:blur(10px);border-radius:12px;padding:15px}"
".input-group{display:flex;justify-content:space-between;align-items:center}"
".input-group input{width:60px;padding:5px;border:none;border-radius:6px;background:"
"rgba(255,255,255,0.2);color:#fff;text-align:center}.btn{width:100%;padding:10px;"
"border:none;border-radius:8px;background:linear-gradient(45deg,#ff6b6b,#ee5a52);"
"color:#fff;font-weight:bold;cursor:pointer}#chart{width:100%!important;height:200px!important;"
"margin-bottom:15px}#current-value{text-align:center;font-size:2rem;margin:10px 0}"
".sensor-data{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:15px}"
".sensor-box{background:rgba(255,255,255,0.1);border-radius:8px;padding:10px;text-align:center}"
"</style></head><body>"
"<div class=\"container\"><h1 class=\"title\">💧 Observação Meteorológica</h1>"
"<div id=\"status\" class=\"status\">Conectando…</div>"
"<div class=\"sensor-data\">"
"<div class=\"sensor-box\"><div>Temp BMP</div><div id=\"temp-bmp\">-- °C</div></div>"
"<div class=\"sensor-box\"><div>Altitude</div><div id=\"altitude\">-- m</div></div>"
"<div class=\"sensor-box\"><div>Temp AHT</div><div id=\"temp-aht\">-- °C</div></div>"
"<div class=\"sensor-box\"><div>Umidade</div><div id=\"humidity\">-- %</div></div>"
"</div>"
"<div id=\"current-value\">--%</div>"
"<canvas id=\"chart\"></canvas><form id=\"limits-form\" class=\"form\">"
"<div class=\"input-group\"><label>Min (%):</label><input type=\"number\" id=\"min-input\" min=\"0\" max=\"100\" required></div>"
"<div class=\"input-group\"><label>Max (%):</label><input type=\"number\" id=\"max-input\" min=\"0\" max=\"100\" required></div>"
"<div class=\"input-group\"><label>Offset:</label><input type=\"number\" id=\"offset-input\" min=\"-100\" max=\"100\" required></div>"
"<button type=\"submit\" class=\"btn\">Salvar</button></form>"
"<div id=\"feedback\" style=\"text-align:center;height:20px;margin-top:5px\"></div></div>"
"<script>"
"const ctx=document.getElementById('chart').getContext('2d'),history=[],maxPts=30,"
"chart=new Chart(ctx,{type:'line',data:{labels:[],datasets:[{label:'Temperatura (%)',data:[],"
"fill:true,tension:0.3,backgroundColor:'rgba(75,192,192,0.2)',borderColor:'rgba(75,192,192,1)',"
"borderWidth:2}]},options:{scales:{x:{display:false},y:{beginAtZero:true,max:100}}}});"
"async function fetchData(){"
"try{const res=await fetch('/api/data');if(!res.ok)throw 0;"
"const d=await res.json();console.log('Dados recebidos:', d);"
"const val=d.nivel_atual;"
"const st=document.getElementById('status');"
"history.push(val);if(history.length>maxPts)history.shift();"
"if(!d.error){st.textContent='OK';st.className='status ok'}else{st.textContent='Erro';st.className='status error'}"
"chart.data.labels=history.map((_,i)=>i);chart.data.datasets[0].data=history;chart.update();"
"const cv=document.getElementById('current-value');cv.textContent=val+'%';"
"if(val<d.min||val>d.max){cv.style.color='#ff6b6b';cv.innerHTML=val+'% <span>⚠</span>'}else cv.style.color='#2ecc71';"
"document.getElementById('temp-bmp').textContent=d.temp_bmp.toFixed(1)+' °C';"
"document.getElementById('altitude').textContent=d.altitude.toFixed(1)+' m';"
"document.getElementById('temp-aht').textContent=d.temp_aht.toFixed(1)+' °C';"
"document.getElementById('humidity').textContent=d.humidity.toFixed(1)+' %';"
"}catch(e){console.log(e);const st=document.getElementById('status');st.textContent='Falha';st.className='status error';"
"document.getElementById('current-value').textContent='--%'}}"
"async function loadSettings(){"
"try{const res=await fetch('/api/data'),d=await res.json();console.log('Configurações:', d);"
"document.getElementById('min-input').value=d.min;document.getElementById('max-input').value=d.max;"
"document.getElementById('offset-input').value=d.offset}catch{}}"
"document.getElementById('limits-form').addEventListener('submit',async e=>{"
"e.preventDefault();const min=parseInt(document.getElementById('min-input').value),"
"max=parseInt(document.getElementById('max-input').value),off=parseInt(document.getElementById('offset-input').value),"
"fb=document.getElementById('feedback');if(min>=max){fb.style.color='#e74c3c';fb.textContent='Min<Max';return}"
"if(min<0||max>100||off<-100||off>100){fb.style.color='#e74c3c';fb.textContent='Valor inválido';return}"
"try{fb.textContent='Salvando...';fb.style.color='#3498db';"
"const r=await fetch('/api/limites',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:`min=${min}&max=${max}&offset=${off}`});if(!r.ok)throw 0;"
"fb.textContent='Salvo';fb.style.color='#2ecc71';setTimeout(fetchData,500)}"
"catch{fb.style.color='#e74c3c';fb.textContent='Erro ao salvar'}});"
"fetchData();setInterval(fetchData,2000);loadSettings()"
"</script></body></html>";