const char HTML_BODY[] =
"<!DOCTYPE html>"
"<html lang=\"pt-br\">"
"<head>"
  "<meta charset=\"UTF-8\">"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  "<title>Observação Meteorológica</title>"
  "<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>"
  "<style>"
    "*{margin:0;padding:0;box-sizing:border-box}"
    "body{font-family:system-ui;-apple-system,sans-serif;background:#667eea;color:#fff;display:flex;justify-content:center;align-items:center;min-height:100vh;padding:20px}"
    ".container{width:100%;max-width:480px;background:rgba(255,255,255,0.1);backdrop-filter:blur(20px);border-radius:16px;padding:20px}"
    ".title{text-align:center;font-size:1.6rem;margin-bottom:20px;font-weight:300}"
    ".status{margin-bottom:15px;text-align:center;padding:10px;border-radius:8px;font-weight:bold}"
    ".ok{background:rgba(46,204,113,0.25);border:2px solid #2ecc71}"
    ".error{background:rgba(231,76,60,0.25);border:2px solid #e74c3c}"
    ".form{display:grid;gap:10px;background:rgba(255,255,255,0.1);backdrop-filter:blur(10px);border-radius:12px;padding:15px}"
    ".input-group{display:flex;justify-content:space-between;align-items:center}"
    ".input-group label{font-size:1rem}"
    ".input-group input{width:60px;padding:5px;border:none;border-radius:6px;background:rgba(255,255,255,0.2);color:#fff;text-align:center}"
    ".btn{width:100%;padding:10px;border:none;border-radius:8px;background:linear-gradient(45deg,#ff6b6b,#ee5a52);color:#fff;font-weight:bold;cursor:pointer}"
    "#chart{width:100%!important;height:200px!important;margin-bottom:15px}"
    "#current-value{text-align:center;font-size:2rem;margin:10px 0}"
  "</style>"
"</head>"
"<body>"
  "<div class=\"container\">"
    "<h1 class=\"title\">💧 Observação Meteorológica</h1>"
    "<div id=\"status\" class=\"status\">Conectando…</div>"
    "<div id=\"current-value\">--%</div>"
    "<canvas id=\"chart\"></canvas>"
    "<form id=\"limits-form\" class=\"form\">"
      "<div class=\"input-group\"><label>Min (%):</label><input type=\"number\" id=\"min-input\" min=\"0\" max=\"100\" required></div>"
      "<div class=\"input-group\"><label>Max (%):</label><input type=\"number\" id=\"max-input\" min=\"0\" max=\"100\" required></div>"
      "<div class=\"input-group\"><label>Offset:</label><input type=\"number\" id=\"offset-input\" min=\"-100\" max=\"100\" required></div>"
      "<button type=\"submit\" class=\"btn\">Salvar</button>"
    "</form>"
    "<div id=\"feedback\" style=\"text-align:center;height:20px;margin-top:5px\"></div>"
  "</div>"

  "<script>"
    "const ctx = document.getElementById('chart').getContext('2d');"
    "const history = [];"
    "const maxPts = 30;"
    "const chart = new Chart(ctx, {"
      "type: 'line',"
      "data: { labels: [], datasets: [{ "
        "label: 'Nível (%)', "
        "data: [], "
        "fill: true, "
        "tension: 0.3,"
        "backgroundColor: 'rgba(75, 192, 192, 0.2)',"
        "borderColor: 'rgba(75, 192, 192, 1)',"
        "borderWidth: 2"
      "}] },"
      "options: { scales:{ x:{display:false}, y:{beginAtZero:true, max:100} } }"
    "});"

    "async function fetchData(){"
      "try{"
        "const res = await fetch('/api/data');"
        "if(!res.ok) throw 0;"
        "const d = await res.json();"
        "let val = d.nivel_atual + (d.offset||0);"
        "if(val<0) val=0; if(val>100) val=100;"
        "history.push(val); if(history.length>maxPts) history.shift();"
        "const st = document.getElementById('status');"
        "if(!d.error){ st.textContent='OK'; st.className='status ok'; }"
        "else{ st.textContent='Erro'; st.className='status error'; }"
        "chart.data.labels = history.map((_,i)=>i);"
        "chart.data.datasets[0].data = history;"
        "chart.update();"
        
        "// Atualiza valor atual"
        "const currentValue = document.getElementById('current-value');"
        "currentValue.textContent = `${val}%`;"
        "if(val < d.min || val > d.max) {"
          "currentValue.style.color = '#ff6b6b';"
          "currentValue.innerHTML = `${val}% <i style=\"font-size:1.5rem\">⚠️</i>`;"
        "} else {"
          "currentValue.style.color = '#2ecc71';"
        "}"
      "}catch{"
        "const st = document.getElementById('status');"
        "st.textContent='Falha na conexão'; st.className='status error';"
        "document.getElementById('current-value').textContent = '--%';"
      "}"
    "}"

    "async function loadCurrentSettings() {"
      "try {"
        "const res = await fetch('/api/data');"
        "if(!res.ok) throw new Error('Failed to load settings');"
        "const data = await res.json();"
        "document.getElementById('min-input').value = data.min;"
        "document.getElementById('max-input').value = data.max;"
        "document.getElementById('offset-input').value = data.offset;"
      "} catch(error) {"
        "console.error('Error loading settings:', error);"
      "}"
    "}"

    "document.getElementById('limits-form').addEventListener('submit', async e=>{"
      "e.preventDefault();"
      "const min = parseInt(document.getElementById('min-input').value),"
            "max = parseInt(document.getElementById('max-input').value),"
            "off = parseInt(document.getElementById('offset-input').value),"
            "fb = document.getElementById('feedback');"
      "if(min>=max){ fb.style.color='#e74c3c'; fb.textContent='Min deve ser menor que Max'; return; }"
      "if(min < 0 || max > 100 || off < -100 || off > 100) {"
        "fb.style.color='#e74c3c';"
        "fb.textContent='Valores fora do intervalo permitido';"
        "return;"
      "}"
      "try{"
        "fb.textContent = 'Salvando...';"
        "fb.style.color = '#3498db';"
        "const body = new URLSearchParams({min, max, offset:off});"
        "const r = await fetch('/api/limites',{"
          "method:'POST',"
          "headers:{'Content-Type':'application/x-www-form-urlencoded'},"
          "body"
        "});"
        "if(!r.ok) throw 0;"
        "fb.style.color='#2ecc71'; fb.textContent='Salvo com sucesso!';"
        "// Atualiza os dados após salvar"
        "setTimeout(fetchData, 500);"
      "}catch{"
        "fb.style.color='#e74c3c'; fb.textContent='Erro ao salvar. Tente novamente.';"
      "}"
    "});"

    "fetchData(); "
    "setInterval(fetchData,2000);"
    "loadCurrentSettings();"
  "</script>"
"</body>"
"</html>";